<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\Indy3DModInstaller.ico</ApplicationIcon>
    <Version>2.3.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\Indy3DModInstaller.ico" />
  </ItemGroup>

</Project>
